config/routes.rb
Rails.application.routes.draw do
  resources :misc_promotional_rules

  resources :promotional_rules

  resources :carts_products

  resources :carts

  devise_for :users, path: "", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  resources :products

  root 'products#index'

  resources :search do
    get 'index', :on => :collection
    post 'index', :on => :collection
  end

end

app/models/misc_promotional_rule.rb
class MiscPromotionalRule < ActiveRecord::Base
  validates :name, presence:true, uniqueness: true
  validates :discount_price, numericality: {:greater_than => 0}
end

app/controllers/misc_promotional_rules_controller.rb
class MiscPromotionalRulesController < ApplicationController
  before_action :set_misc_promotional_rule, only: [:show, :edit, :update, :destroy]

  # GET /misc_promotional_rules
  # GET /misc_promotional_rules.json
  def index
    @misc_promotional_rules = MiscPromotionalRule.all
  end

  # GET /misc_promotional_rules/1
  # GET /misc_promotional_rules/1.json
  def show
  end

  # GET /misc_promotional_rules/new
  def new
    @misc_promotional_rule = MiscPromotionalRule.new
  end

  # GET /misc_promotional_rules/1/edit
  def edit
  end

  # POST /misc_promotional_rules
  # POST /misc_promotional_rules.json
  def create
    @misc_promotional_rule = MiscPromotionalRule.new(misc_promotional_rule_params)

    respond_to do |format|
      if @misc_promotional_rule.save
        format.html { redirect_to @misc_promotional_rule, notice: 'Misc promotional rule was successfully created.' }
        format.json { render :show, status: :created, location: @misc_promotional_rule }
      else
        format.html { render :new }
        format.json { render json: @misc_promotional_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /misc_promotional_rules/1
  # PATCH/PUT /misc_promotional_rules/1.json
  def update
    respond_to do |format|
      if @misc_promotional_rule.update(misc_promotional_rule_params)
        format.html { redirect_to @misc_promotional_rule, notice: 'Misc promotional rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @misc_promotional_rule }
      else
        format.html { render :edit }
        format.json { render json: @misc_promotional_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /misc_promotional_rules/1
  # DELETE /misc_promotional_rules/1.json
  def destroy
    @misc_promotional_rule.destroy
    respond_to do |format|
      format.html { redirect_to misc_promotional_rules_url, notice: 'Misc promotional rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_misc_promotional_rule
      @misc_promotional_rule = MiscPromotionalRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def misc_promotional_rule_params
      params.require(:misc_promotional_rule).permit(:name, :discount_percentage, :discount_price)
    end
end

app/helpers/misc_promotional_rules_helper.rb
module MiscPromotionalRulesHelper
end

app/views/misc_promotional_rules/_form.html.erb
<%= form_for(@misc_promotional_rule) do |f| %>
  <% if @misc_promotional_rule.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@misc_promotional_rule.errors.count, "error") %> prohibited this misc_promotional_rule from being saved:</h2>

      <ul>
      <% @misc_promotional_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.select :name, options_for_select(ENTITY_NAMES, @misc_promotional_rule.name), {},  {:class=>"form-control"}%>
  </div>
  <div class="form-group">
    <%= f.label :discount_percentage %> %
    <%= f.select :discount_percentage, options_for_select((0..100).to_a, @misc_promotional_rule.discount_percentage.to_i), {},  {:class=>"form-control"}%>
  </div>
  <div class="form-group">
    <%= f.label :discounted_price %> £
    <%= f.text_field :discount_price, :class=>"form-control"%>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/misc_promotional_rules/edit.html.erb
<h1>Editing Misc Promotional Rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @misc_promotional_rule %> |
<%= link_to 'Back', misc_promotional_rules_path %>

app/views/misc_promotional_rules/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Misc Promotional Rules</h3>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Discount percentage</th>
      <th>Discount price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @misc_promotional_rules.each do |misc_promotional_rule| %>
    <tr>
      <td><%= misc_promotional_rule.name %></td>
      <td><%= misc_promotional_rule.discount_percentage %> %</td>
      <td><%= number_to_currency(misc_promotional_rule.discount_price) %></td>
      <td>
        <div class="pull-right">
        <%= link_to 'Show', misc_promotional_rule , :class=>"btn btn-success btn-sm"%>
        <%= link_to 'Edit', edit_misc_promotional_rule_path(misc_promotional_rule) , :class=>"btn btn-info btn-sm"%>
        <%= link_to 'Destroy', misc_promotional_rule, method: :delete, data: { confirm: 'Are you sure?' } , :class=>"btn btn-danger btn-sm"%>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Misc promotional rule', new_misc_promotional_rule_path %>

app/views/misc_promotional_rules/new.html.erb
<h1>New Misc Promotional Rule</h1>

<%= render 'form' %>

<%= link_to 'Back', misc_promotional_rules_path %>

app/views/misc_promotional_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @misc_promotional_rule.name %>
</p>

<p>
  <strong>Discount percentage:</strong>
  <%= @misc_promotional_rule.discount_percentage %> %
</p>

<p>
  <strong>Discount price:</strong>
  <%= number_to_currency @misc_promotional_rule.discount_price %>
</p>

<%= link_to 'Edit', edit_misc_promotional_rule_path(@misc_promotional_rule) %> |
<%= link_to 'Back', misc_promotional_rules_path %>