config/routes.rb
Rails.application.routes.draw do
  resources :misc_promotional_rules

  resources :promotional_rules

  resources :carts_products

  resources :carts

  devise_for :users, path: "", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  resources :products

  root 'products#index'

  resources :search do
    get 'index', :on => :collection
    post 'index', :on => :collection
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessor :total_after_discount
  belongs_to :user
  has_many :carts_products
  has_many :products, through: :carts_products

  def scan(product)
    products << product
  end

  def total
    products.sum('price')
  end

  def apply_promotional_rules(all_promotional_rules)

    discount = 0
    discounted_price = total

    all_promotional_rules[:promotional_rules].each do |promotional_rule|
      product = promotional_rule.product
      discounted_products = products.where(name:product.name)
      if discounted_products.length >= promotional_rule.quantity
        discount = discount + ((discounted_products.first.price - promotional_rule.discount_price) * discounted_products.length)
        discounted_price = discounted_price - discount
      end
    end
    # discounted_products = products.where(name:'Travel Card Holder')
    # if discounted_products.length >= 2
    #   discount = discount + ((discounted_products.first.price - 8.50) * discounted_products.length)
    #   discounted_price = discounted_price - discount
    # end


    all_promotional_rules[:misc_promotional_rules].each do |misc_promotional_rule|
      if (total > misc_promotional_rule.discount_price)
        discount = (total * misc_promotional_rule.discount_percentage/100)
        discounted_price = discounted_price - discount
      end
    end
    # if (total > 60)
    #   discount = (total * 10/100)
    #   discounted_price = discounted_price - discount
    # end

    @total_after_discount = discounted_price
  end

  def discount_percentage
    ((total - @total_after_discount)/total * 100)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:quantity, :user_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h3>Listing Carts</h3>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.quantity %></td>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>